# Generated by Django 3.2.5 on 2021-11-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='year',
            field=models.CharField(max_length=11),
        ),
    ]
