# Generated by Django 3.2.5 on 2021-11-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontApp', '0003_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='MySkill',
        ),
    ]
