# Generated by Django 3.2.5 on 2021-11-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontApp', '0004_rename_skill_myskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='myskill',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
