# Generated by Django 3.2.5 on 2021-11-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontApp', '0005_myskill_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
