# Generated by Django 3.2.5 on 2021-11-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontApp', '0006_learningmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmap',
            name='technology',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learningmap',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
